### ISSUE TITLE
How did you get this file : tianchi_train_jsons.txt

### ISSUE THREAD

**Issue by Judioljuse** [WhatAShot/Electrocardio-Panorama#10]
Is this file obtained through AnnotationTools annotation, any answers will be greatly appreciated！

**Comment by upzheng** [comment]
Hello, 
When the AnnotationTools is used to complete the annotation, a lot of json files will be generated. Next, the entire dataset will be splited into a train dataset and  test dataset(or they have already been splited). The json file name of  train data will be written into tianchi_train_jsons.txt, and the json file name of test dataset will be written into tianchi_test_jsons.txt.
I hope it can help you.
