### ISSUE TITLE
How did you get this file : data/PTB/pkl_data/train_heartbeats.pkl

### ISSUE THREAD

**Issue by Judioljuse** [WhatAShot/Electrocardio-Panorama#11]
Any answers will be greatly appreciated！

**Comment by Judioljuse** [comment]
And what is the difference with 'data/ptb/ptb_pkl_data/train_ptb.pkl',If it is convenient for you, can you provide the data of the above ptb.

**Comment by upzheng** [comment]
Hi Judioljuse,
There is something wrong with 'code/README.md' about pre-processed data url of PTB.
You can now download the PTB pre-processed data in this url: https://drive.google.com/file/d/1eAU9zeu4x4oXwe2GFnLoDaxs-EQ1TgKm/view?usp=sharing
And the README file mentioned above is already corrected.
