### ISSUE TITLE
Tianchi Dataset

### ISSUE THREAD

**Issue by leotat123** [WhatAShot/Electrocardio-Panorama#14]
Hello, dear @WhatAShot , I have a query regarding the Tianchi data. I don't know if you can share the .txt files of the ecgs because publicly I only find h2_round.
Thanks for you help
Regards

**Comment by WhatAShot** [comment]
Thank you for your interest. Due to the license, we are not allowed to share raw tianchi datasets. However, maybe you can write to the officiers for the data. Thank you.
